require('mattomatteo.options')
require("mattomatteo.packages")
require("mattomatteo.patches")
require('mattomatteo.appearance')
require('mattomatteo.lsp')
require('mattomatteo.vsnip')
require('mattomatteo.treesitter')
require('mattomatteo.formatter_settings')
require('mattomatteo.lualine_config')
require('mattomatteo.commenter_config')
require('mattomatteo.keybindings.mappings')
require('mattomatteo.telescope')
require('mattomatteo.vimtex')
require('mattomatteo.indentbl')
require('mattomatteo.autocommands')
require('mattomatteo.dap')
-- require('mattomatteo.tailwind')
